steps:
- name: gcr.io/cloud-builders/docker
  args: ['build',
          '-t','gcr.io/$PROJECT_ID/google-spreadsheet-api:${SHORT_SHA}',
          '-t','gcr.io/$PROJECT_ID/google-spreadsheet-api:latest-SNAPSHOT',
          '.']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/google-spreadsheet-api:${SHORT_SHA}']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/google-spreadsheet-api:latest-SNAPSHOT']
- name: gcr.io/cloud-builders/kubectl
  args: ['-n','$_K8S_NS','set','image','deployment','google-spreadsheet-api','gcr.io/$PROJECT_ID/google-spreadsheet-api:${SHORT_SHA}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=web-test'
timeout: "1800s"
images:
  - 'gcr.io/$PROJECT_ID/google-spreadsheet-api:${SHORT_SHA}'
  - 'gcr.io/$PROJECT_ID/google-spreadsheet-api:latest-SNAPSHOT'